export const PAKISTAN_CITIES = [
  // Punjab Cities
  { value: 'Lahore', label: 'Lahore' },
  { value: 'Faisalabad', label: 'Faisalabad' },
  { value: 'Multan', label: 'Multan' },
  { value: 'Rawalpindi', label: 'Rawalpindi' },
  { value: 'Gujranwala', label: 'Gujranwala' },
  { value: 'Sialkot', label: 'Sialkot' },
  { value: 'Bahawalpur', label: 'Bahawalpur' },
  { value: 'Sargodha', label: 'Sargodha' },
  { value: 'Jhelum', label: 'Jhelum' },
  { value: 'Gujrat', label: 'Gujrat' },
  { value: 'Sheikhupura', label: 'Sheikhupura' },
  { value: 'Jhang', label: 'Jhang' },
  { value: 'Sahiwal', label: 'Sahiwal' },
  { value: 'Okara', label: 'Okara' },
  { value: 'Kasur', label: 'Kasur' },
  { value: 'Pakpattan', label: 'Pakpattan' },
  { value: 'Attock', label: 'Attock' },
  { value: 'Chakwal', label: 'Chakwal' },
  { value: 'Mianwali', label: 'Mianwali' },
  { value: 'Bhakkar', label: 'Bhakkar' },
  { value: 'Khushab', label: 'Khushab' },
  { value: 'Layyah', label: 'Layyah' },
  { value: 'Vehari', label: 'Vehari' },
  { value: 'Khanewal', label: 'Khanewal' },
  { value: 'Lodhran', label: 'Lodhran' },
  { value: 'Rajanpur', label: 'Rajanpur' },
  { value: 'Dera Ghazi Khan', label: 'Dera Ghazi Khan' },
  { value: 'Muzaffargarh', label: 'Muzaffargarh' },
  { value: 'Bahawalnagar', label: 'Bahawalnagar' },
  { value: 'Chiniot', label: 'Chiniot' },
  { value: 'Toba Tek Singh', label: 'Toba Tek Singh' },
  { value: 'Nankana Sahib', label: 'Nankana Sahib' },
  { value: 'Hafizabad', label: 'Hafizabad' },
  { value: 'Mandi Bahauddin', label: 'Mandi Bahauddin' },
  { value: 'Narowal', label: 'Narowal' },
  { value: 'Gojra', label: 'Gojra' },
  { value: 'Daska', label: 'Daska' },
  { value: 'Wazirabad', label: 'Wazirabad' },
  { value: 'Kamoke', label: 'Kamoke' },
  { value: 'Muridke', label: 'Muridke' },
  { value: 'Kot Addu', label: 'Kot Addu' },
  { value: 'Taunsa', label: 'Taunsa' },
  { value: 'Raiwind', label: 'Raiwind' },
  { value: 'Shahdara', label: 'Shahdara' },
  { value: 'Gulberg', label: 'Gulberg' },
  { value: 'Model Town', label: 'Model Town' },
  { value: 'Defence', label: 'Defence' },
  { value: 'Cantt', label: 'Cantt' },
  { value: 'Garden Town', label: 'Garden Town' },
  { value: 'Iqbal Town', label: 'Iqbal Town' },
  { value: 'Samundri', label: 'Samundri' },

  // Sindh Cities
  { value: 'Karachi', label: 'Karachi' },
  { value: 'Hyderabad', label: 'Hyderabad' },
  { value: 'Sukkur', label: 'Sukkur' },
  { value: 'Larkana', label: 'Larkana' },
  { value: 'Nawabshah', label: 'Nawabshah' },
  { value: 'Mirpur Khas', label: 'Mirpur Khas' },
  { value: 'Jacobabad', label: 'Jacobabad' },
  { value: 'Shikarpur', label: 'Shikarpur' },
  { value: 'Dadu', label: 'Dadu' },
  { value: 'Thatta', label: 'Thatta' },
  { value: 'Badin', label: 'Badin' },
  { value: 'Sanghar', label: 'Sanghar' },
  { value: 'Naushahro Firoze', label: 'Naushahro Firoze' },
  { value: 'Ghotki', label: 'Ghotki' },
  { value: 'Khairpur', label: 'Khairpur' },
  { value: 'Umerkot', label: 'Umerkot' },
  { value: 'Tando Muhammad Khan', label: 'Tando Muhammad Khan' },
  { value: 'Tando Allahyar', label: 'Tando Allahyar' },
  { value: 'Matli', label: 'Matli' },
  { value: 'Tando Adam', label: 'Tando Adam' },
  { value: 'Sehwan', label: 'Sehwan' },
  { value: 'Moro', label: 'Moro' },
  { value: 'Sakrand', label: 'Sakrand' },
  { value: 'Shahdadpur', label: 'Shahdadpur' },
  { value: 'Hala', label: 'Hala' },
  { value: 'Matiari', label: 'Matiari' },
  { value: 'Tando Jam', label: 'Tando Jam' },
  { value: 'Digri', label: 'Digri' },
  { value: 'Kotri', label: 'Kotri' },
  { value: 'Jamshoro', label: 'Jamshoro' },
  { value: 'Kandhkot', label: 'Kandhkot' },
  { value: 'Kashmore', label: 'Kashmore' },
  { value: 'Lakhi', label: 'Lakhi' },
  { value: 'Khanpur', label: 'Khanpur' },
  { value: 'Ranipur', label: 'Ranipur' },
  { value: 'Shahdadkot', label: 'Shahdadkot' },
  { value: 'Dera Allahyar', label: 'Dera Allahyar' },
  { value: 'Gambat', label: 'Gambat' },
  { value: 'Nasirabad', label: 'Nasirabad' },
  { value: 'Mehrabpur', label: 'Mehrabpur' },
  { value: 'Rohri', label: 'Rohri' },
  { value: 'Pano Aqil', label: 'Pano Aqil' },
  { value: 'Chhor', label: 'Chhor' },
  { value: 'Kunri', label: 'Kunri' },
  { value: 'Pithoro', label: 'Pithoro' },
  { value: 'Samaro', label: 'Samaro' },
  { value: 'Goth Garelo', label: 'Goth Garelo' },
  { value: 'Dokri', label: 'Dokri' },
  { value: 'Dingro', label: 'Dingro' },
  { value: 'Ubauro', label: 'Ubauro' },
  { value: 'Sadiqabad', label: 'Sadiqabad' },
  { value: 'Liaquatpur', label: 'Liaquatpur' },
  { value: 'Uch Sharif', label: 'Uch Sharif' },
  { value: 'Alipur', label: 'Alipur' },
  { value: 'Jatoi', label: 'Jatoi' },
  { value: 'Layyah', label: 'Layyah' },
  { value: 'Chobara', label: 'Chobara' },
  { value: 'Kot Sultan', label: 'Kot Sultan' },
  { value: 'Darya Khan', label: 'Darya Khan' },
  { value: 'Kallur Kot', label: 'Kallur Kot' },
  { value: 'Mankera', label: 'Mankera' },
  { value: 'Dullewala', label: 'Dullewala' },
  { value: 'Daud Khel', label: 'Daud Khel' },
  { value: 'Pindi Gheb', label: 'Pindi Gheb' },
  { value: 'Fateh Jang', label: 'Fateh Jang' },
  { value: 'Gujar Khan', label: 'Gujar Khan' },
  { value: 'Kallar Syedan', label: 'Kallar Syedan' },
  { value: 'Taxila', label: 'Taxila' },
  { value: 'Wah Cantonment', label: 'Wah Cantonment' },
  { value: 'Murree', label: 'Murree' },
  { value: 'Kahuta', label: 'Kahuta' },
  { value: 'Kotli Sattian', label: 'Kotli Sattian' },

  // Khyber Pakhtunkhwa Cities
  { value: 'Peshawar', label: 'Peshawar' },
  { value: 'Mardan', label: 'Mardan' },
  { value: 'Abbottabad', label: 'Abbottabad' },
  { value: 'Swat', label: 'Swat' },
  { value: 'Mansehra', label: 'Mansehra' },
  { value: 'Swabi', label: 'Swabi' },
  { value: 'Charsadda', label: 'Charsadda' },
  { value: 'Nowshera', label: 'Nowshera' },
  { value: 'Kohat', label: 'Kohat' },
  { value: 'Bannu', label: 'Bannu' },
  { value: 'Dera Ismail Khan', label: 'Dera Ismail Khan' },
  { value: 'Lakki Marwat', label: 'Lakki Marwat' },
  { value: 'Tank', label: 'Tank' },
  { value: 'Hangu', label: 'Hangu' },
  { value: 'Karak', label: 'Karak' },
  { value: 'Buner', label: 'Buner' },
  { value: 'Shangla', label: 'Shangla' },
  { value: 'Upper Dir', label: 'Upper Dir' },
  { value: 'Lower Dir', label: 'Lower Dir' },
  { value: 'Malakand', label: 'Malakand' },
  { value: 'Chitral', label: 'Chitral' },
  { value: 'Kohistan', label: 'Kohistan' },
  { value: 'Tor Ghar', label: 'Tor Ghar' },
  { value: 'Battagram', label: 'Battagram' },
  { value: 'Haripur', label: 'Haripur' },
  { value: 'Batagram', label: 'Batagram' },

  // Balochistan Cities
  { value: 'Quetta', label: 'Quetta' },
  { value: 'Turbat', label: 'Turbat' },
  { value: 'Khuzdar', label: 'Khuzdar' },
  { value: 'Kalat', label: 'Kalat' },
  { value: 'Mastung', label: 'Mastung' },
  { value: 'Sibi', label: 'Sibi' },
  { value: 'Zhob', label: 'Zhob' },
  { value: 'Loralai', label: 'Loralai' },
  { value: 'Barkhan', label: 'Barkhan' },
  { value: 'Musakhel', label: 'Musakhel' },
  { value: 'Killa Saifullah', label: 'Killa Saifullah' },
  { value: 'Pishin', label: 'Pishin' },
  { value: 'Killa Abdullah', label: 'Killa Abdullah' },
  { value: 'Chagai', label: 'Chagai' },
  { value: 'Nushki', label: 'Nushki' },
  { value: 'Washuk', label: 'Washuk' },
  { value: 'Awaran', label: 'Awaran' },
  { value: 'Panjgur', label: 'Panjgur' },
  { value: 'Gwadar', label: 'Gwadar' },
  { value: 'Lasbela', label: 'Lasbela' },
  { value: 'Jhal Magsi', label: 'Jhal Magsi' },
  { value: 'Kachhi', label: 'Kachhi' },
  { value: 'Jaffarabad', label: 'Jaffarabad' },
  { value: 'Nasirabad', label: 'Nasirabad' },
  { value: 'Kohlu', label: 'Kohlu' },
  { value: 'Dera Bugti', label: 'Dera Bugti' },

  // Islamabad Capital Territory
  { value: 'Islamabad', label: 'Islamabad' },

  // Gilgit-Baltistan Cities
  { value: 'Gilgit', label: 'Gilgit' },
  { value: 'Skardu', label: 'Skardu' },
  { value: 'Chilas', label: 'Chilas' },
  { value: 'Astore', label: 'Astore' },
  { value: 'Ghizer', label: 'Ghizer' },
  { value: 'Hunza', label: 'Hunza' },
  { value: 'Nagar', label: 'Nagar' },
  { value: 'Diamer', label: 'Diamer' },
  { value: 'Ghanche', label: 'Ghanche' },
  { value: 'Shigar', label: 'Shigar' },
  { value: 'Kharmang', label: 'Kharmang' },
  { value: 'Roundu', label: 'Roundu' },

  // Azad Kashmir Cities
  { value: 'Muzaffarabad', label: 'Muzaffarabad' },
  { value: 'Mirpur', label: 'Mirpur' },
  { value: 'Rawalakot', label: 'Rawalakot' },
  { value: 'Kotli', label: 'Kotli' },
  { value: 'Bhimber', label: 'Bhimber' },
  { value: 'Bagh', label: 'Bagh' },
  { value: 'Haveli', label: 'Haveli' },
  { value: 'Neelum', label: 'Neelum' },
  { value: 'Poonch', label: 'Poonch' },
  { value: 'Sudhnuti', label: 'Sudhnuti' },
  { value: 'Hajira', label: 'Hajira' },
  { value: 'Forward Kahuta', label: 'Forward Kahuta' },
  { value: 'Nakyal', label: 'Nakyal' },
  { value: 'Pallandri', label: 'Pallandri' },
  { value: 'Thorar', label: 'Thorar' },
  { value: 'Beri Pat', label: 'Beri Pat' },
  { value: 'Chakswari', label: 'Chakswari' },
  { value: 'Dadyal', label: 'Dadyal' },
  { value: 'Khuiratta', label: 'Khuiratta' },
  { value: 'Samahni', label: 'Samahni' },
  { value: 'Sehnsa', label: 'Sehnsa' },
  { value: 'Tatrinote', label: 'Tatrinote' },
  { value: 'Trarkhel', label: 'Trarkhel' },
  { value: 'Uthmankhel', label: 'Uthmankhel' },
  { value: 'Watala', label: 'Watala' },
  { value: 'Zafarwal', label: 'Zafarwal' }
].sort((a, b) => a.label.localeCompare(b.label));
